# Generated by Django 3.0.5 on 2020-04-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationsections', '0003_content_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Сущность', 'verbose_name_plural': 'Сущности'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AlterField(
            model_name='content',
            name='pub_date',
            field=models.DateField(verbose_name='дата публикации'),
        ),
    ]
